name: cloud-run-laravel8-deploy
on:
  push:
    branches:
      - newbranch
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # gcloud CLI のセットアップ
      - uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          service_account_email: ${{ secrets.TEST_GCP_EMAIL }}
          service_account_key: ${{ secrets.TEST_GCP_CREDENTIALS }}
          export_default_credentials: true

      # 必要なAPIを有効化
      - name: Enable APIs
        run: |
          gcloud services enable sqladmin.googleapis.com \
          --project "$TEST_GCP_PROJECT_LOWER"

      # .envファイルをデコード
      - name: Decode .env file
        run: |
          echo ${{ secrets.TEST_ENV_FILE }} | base64 --decode > src/.env

      # Dockerの認証を設定
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # シークレットを小文字に変換
      - name: Convert secrets to lowercase
        run: |
          export TEST_GCP_PROJECT_LOWER=$(echo "${{ secrets.TEST_GCP_PROJECT }}" | tr '[:upper:]' '[:lower:]')
          export TEST_GCP_APPLICATION_LOWER=$(echo "${{ secrets.TEST_GCP_APPLICATION }}" | tr '[:upper:]' '[:lower:]')
          echo "TEST_GCP_PROJECT_LOWER=$TEST_GCP_PROJECT_LOWER" >> $GITHUB_ENV
          echo "TEST_GCP_APPLICATION_LOWER=$TEST_GCP_APPLICATION_LOWER" >> $GITHUB_ENV

      # Dockerイメージをビルド
      - name: Build
        run: |
          gcloud config set project "$TEST_GCP_PROJECT_LOWER"
          docker build -f docker/Dockerfile.prod -t asia.gcr.io/$TEST_GCP_PROJECT_LOWER/$TEST_GCP_APPLICATION_LOWER .

      # Dockerイメージをプッシュ
      - name: Push
        run: |
          docker push asia.gcr.io/$TEST_GCP_PROJECT_LOWER/$TEST_GCP_APPLICATION_LOWER

      # GKEクラスタにDockerイメージをデプロイ
      - name: Deploy
        run: |
          gcloud run deploy $TEST_GCP_APPLICATION_LOWER \
          --image asia.gcr.io/$TEST_GCP_PROJECT_LOWER/$TEST_GCP_APPLICATION_LOWER \
          --region asia-east1 \
          --platform=managed \
          --add-cloudsql-instances ${{ secrets.TEST_SQL_CONNECTION_NAME }} \
          --allow-unauthenticated



