name: cloud-run-laravel8-deploy
on:
  push:
    branches:
      - newbranch
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          service_account_email: ${{ secrets.TEST_GCP_EMAIL }}
          service_account_key: ${{ secrets.TEST_GCP_CREDENTIALS }}
          export_default_credentials: true

      # Decode and put .env file
      # https://casualdevelopers.com/tech-tips/how-to-use-dotenv-with-base64-on-circleci/
      - name: Decode .env file
        run: |
          echo ${{ secrets.TEST_ENV_FILE }} | base64 --decode > src/.env

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Convert secrets to lowercase
      - name: Convert secrets to lowercase
        run: |
          export TEST_GCP_PROJECT_LOWER=$(echo "${{ secrets.TEST_GCP_PROJECT }}" | tr '[:upper:]' '[:lower:]')
          export TEST_GCP_APPLICATION_LOWER=$(echo "${{ secrets.TEST_GCP_APPLICATION }}" | tr '[:upper:]' '[:lower:]')
          echo "TEST_GCP_PROJECT_LOWER=$TEST_GCP_PROJECT_LOWER" >> $GITHUB_ENV
          echo "TEST_GCP_APPLICATION_LOWER=$TEST_GCP_APPLICATION_LOWER" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build
        run: |
          gcloud config set project "$TEST_GCP_PROJECT_LOWER"
          docker build -f docker/Dockerfile.prod -t asia.gcr.io/$TEST_GCP_PROJECT_LOWER/$TEST_GCP_APPLICATION_LOWER .

      # Push the Docker image
      - name: Push
        run: |
          docker push asia.gcr.io/$TEST_GCP_PROJECT_LOWER/$TEST_GCP_APPLICATION_LOWER

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud run deploy $TEST_GCP_APPLICATION_LOWER \
          --image asia.gcr.io/$TEST_GCP_PROJECT_LOWER/$TEST_GCP_APPLICATION_LOWER \
          --region asia-east1 \
          --platform=managed \
          --add-cloudsql-instances ${{ secrets.TEST_SQL_CONNECTION_NAME }} \
          --allow-unauthenticated